### ISSUE TITLE
What are the pressure measurement scenarios of Shenyu

### ISSUE THREAD

**Issue by kangarooking** [apache/incubator-shenyu#1829]
Our company is conducting pressure test on Shenyu recently. I'd like to ask about the pressure test scenario of Shenyu.

**Comment by yu199195** [comment]
you can run  shenyu, and then test it

**Comment by kangarooking** [comment]
I mean stress test scenario,for example open log or close log ,some performance bottleneck scenario and so on...  it not just  a simple test. I want to get some practical advice. thanks

**Comment by tuohai666** [comment]
Hi @kangarooking , I understand what you want. But it's hard to give a precise scenario (deployments, configurations, etc.), since there are uncertain upstream and downstream services. I would suggest that you just start the benchmark test and try to improve the performance step by step. Once the performance meet your requirement, you will get the best scenario which you want. And the feedback is welcome here, if you'd like to share.

**Comment by hlcen66** [comment]
Excuse me, do you have the pressure test results？
