### ISSUE TITLE
是否支持代理websocket客户端？

### ISSUE THREAD

**Issue by cqleo** [apache/incubator-shenyu#1942]
是否支持代理websocket客户端？

如果支持，有没有相关对接文档？

**Comment by midnight2104** [comment]
hi, here is a doc(2.3.0 version) for websocket: https://shenyu.apache.org/zh/projects/shenyu-2.3.0/websocket-plugin/ . If the version is of another version, check the corresponding version document.



在 2021-08-18 11:45:49，"Johnson.Chen" ***@***.***> 写道：

是否支持代理websocket客户端？

如果支持，有没有相关对接文档？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by midnight2104** [comment]
if you have other question, please in english. now, I'll close it.

**Comment by cqleo** [comment]
> hi, here is a doc(2.3.0 version) for websocket: https://shenyu.apache.org/zh/projects/shenyu-2.3.0/websocket-plugin/ . If the version is of another version, check the corresponding version document. 在 2021-08-18 11:45:49，"Johnson.Chen" ***@***.***> 写道： 是否支持代理websocket客户端？ 如果支持，有没有相关对接文档？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.



> hi, here is a doc(2.3.0 version) for websocket: https://shenyu.apache.org/zh/projects/shenyu-2.3.0/websocket-plugin/ . If the version is of another version, check the corresponding version document. 在 2021-08-18 11:45:49，"Johnson.Chen" ***@***.***> 写道： 是否支持代理websocket客户端？ 如果支持，有没有相关对接文档？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


thanks!

that is what i need !
