### ISSUE TITLE
shenyu支持性

### ISSUE THREAD

**Issue by wxs19920926** [apache/incubator-shenyu#1963]
## Question

shenyu是否支持文件上传、tcp netty的路由转发呢？

**Comment by zhaiweij** [comment]
hi,file upload will bring a great burden to the gateway. It is not recommended to use the gateway to do this function, and it is more recommended to use a file server to implement this function.




在2021年08月23日 ***@***.***> 写道：

Question

shenyu是否支持文件上传、tcp netty的路由转发呢？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
