### ISSUE TITLE
[Volunteer] Add unit test for ShenyuClientRegisterGrpcServiceImpl

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2139]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.admin.service.register.ShenyuClientRegisterGrpcServiceImpl`

you can create `org.apache.shenyu.admin.service.register/ShenyuClientRegisterGrpcServiceImplTest` in  `/test/java` package

**Comment by storv** [comment]
let me try~

**Comment by yu199195** [comment]
@storv  What is the current progress?

**Comment by midnight2104** [comment]
hello , @storv , What is the current progress?

**Comment by storv** [comment]
sry for that i forgot this issue!i'll make it as soon as quickly! sry for that again.



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月16日 13:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [apache/incubator-shenyu] [Volunteer] Add unit test for ShenyuClientRegisterGrpcServiceImpl (#2139) |

hello , @storv , What is the current progress?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by songyuequan** [comment]
> sry for that i forgot this issue!i'll make it as soon as quickly! sry for that again. 发自 网易邮箱大师
> […](#)

hei , @storv , What is the current progress?
