### ISSUE TITLE
[BUG] The stop.sh script can't work in container

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shenyu#2338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The stop.sh script can't work in container, while it can work in a host machine.

### Expected Behavior

The stop.sh script can work in container.

### Steps To Reproduce

In the container:

1. ./start.sh
2. ./stop.sh

### Environment

```markdown
ShenYu version(s): 2.4.1
```

### Anything else?

In a container, there's no uid column when execute ps -ef.

**Comment by jinze1107** [comment]
what should this stop.sh do?

**Comment by nuo-promise** [comment]
> what should this stop.sh do?

stop shenyu-admin.

**Comment by lahmXu** [comment]
I noticed that in a linux system, the thread's pid is in the second column, but in the docker container the thread's pid is in the first column.

Docker container:
![image](https://user-images.githubusercontent.com/31627887/141392843-4d7339d1-b7a4-448e-b3ac-44efc7e9d7d2.png)
Linux:
![image](https://user-images.githubusercontent.com/31627887/141392941-25a150fe-af85-40c3-b937-347b7191996c.png)

and then I think this problem can be solved by `pgrep -f shenyu`

**Comment by tuohai666** [comment]
@lahmXu Thanks for your solution. Can you submit a pr?

**Comment by lahmXu** [comment]
> @lahmXu Thanks for your solution. Can you submit a pr?

ok, If there's no problem with this solution, please assign to me, thanks.

**Comment by tuohai666** [comment]
@lahmXu I would suggest that you provide the test result of the new script run in both container and host.

**Comment by songyuequan** [comment]
Hi~   I just  change   awk  '{print  $2}'    to  awk  '{print $1}'  
It  works  @lahmXu

**Comment by lahmXu** [comment]
> Hi~ I just change awk '{print $2}' to awk '{print $1}' It works @lahmXu

Yes, but the stop.sh file also needs to be used on the linux server, so we need to find a common solution.

**Comment by songyuequan** [comment]
Yes,  you can just  provide  the test result  @lahmXu

**Comment by lahmXu** [comment]
## Solved Problems
1. The stop.sh script can't work in container
2. "ps: unrecognized option: p". This problem was discovered when solving the first problem. 
- This problem is due to openjdk-8-jre-alpine ps is from busybox and it is not included -p switch for ps, so we need to add `RUN apk --no-cache add procps` in Dockerfile.
- error info:
  ![image](https://user-images.githubusercontent.com/31627887/141604312-125caa56-6993-4bcc-b42a-19b070912392.png)

## Test Result
### Docker Container
**Shenyu Admin**
<img width="1375" alt="image-20211113100750658" src="https://user-images.githubusercontent.com/31627887/141604204-7f973c87-742a-40c2-abf8-72bd4ac10aec.png">

**Shenyu Bootstrap**
![image-20211113101128530](https://user-images.githubusercontent.com/31627887/141604193-7e0b4d0c-9510-4bcb-82ea-4eeac95926fa.png)

### Linux Server
**Shenyu Admin**
<img width="1092" alt="image-20211113103905579" src="https://user-images.githubusercontent.com/31627887/141604215-10d64c3f-bec7-4cea-94c5-2cb5039a8f59.png">

**Shenyu Bootstrap**
<img width="1095" alt="image-20211113104154048" src="https://user-images.githubusercontent.com/31627887/141604220-76dbcd1d-9c8e-467d-a1f5-87e2a94ced3e.png">

**Comment by songyuequan** [comment]
> ## Solved Problems
> 1. The stop.sh script can't work in container
> 2. "ps: unrecognized option: p". This problem was discovered when solving the first problem.
> 
> * This problem is due to openjdk-8-jre-alpine ps is from busybox and it is not included -p switch for ps, so we need to add `RUN apk --no-cache add procps` in Dockerfile.
> * error info:
>   ![image](https://user-images.githubusercontent.com/31627887/141604312-125caa56-6993-4bcc-b42a-19b070912392.png)
> 
> ## Test Result
> ### Docker Container
> **Shenyu Admin** <img alt="image-20211113100750658" width="1375" src="https://user-images.githubusercontent.com/31627887/141604204-7f973c87-742a-40c2-abf8-72bd4ac10aec.png">
> 
> **Shenyu Bootstrap** ![image-20211113101128530](https://user-images.githubusercontent.com/31627887/141604193-7e0b4d0c-9510-4bcb-82ea-4eeac95926fa.png)
> 
> ### Linux Server
> **Shenyu Admin** ![image](https://user-images.githubusercontent.com/31627887/141604568-409a2d69-6dc6-4f22-af43-98e956d0cf32.png)
> 
> **Shenyu Bootstrap** ![image](https://user-images.githubusercontent.com/31627887/141604640-d0aec7d2-49d9-403c-a5b0-55ce7c06e595.png)

I  just  test  the  new  script .  It work both in the host ( Linux and MAC) and  container

**Comment by songyuequan** [comment]
I just test the new script  in  [pr 2352](https://github.com/apache/incubator-shenyu/pull/2353/files) . It work both in the host ( Linux and MAC) and container
