### ISSUE TITLE
【Code Clean】Remove warning codes in apache shenyu

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2366]
### Volunteer help

Hi Community:

As the functionality of the apache shenyu project becomes more and more perfect.

Now apache shenyu has 100+ sub-projects and the amount of code is getting bigger and bigger.

To enhance the quality and readability of the code,and code design.

The project modules involved in this activity are deliberately launched as follows (code includes test code):

- [ ]  sheyun-admin @prospect167 
- [ ]  shenyu-client @qicz 
- [ ] shenyu-common @qinxu2015
- [ ] shenyu-disruptor @songyuequan 
- [ ] shenyu-examples @li-keguo 
- [ ] shenyu-integrated-test @lxl910128 
- [ ] shenyu-loadbalancer @haibo-duan 
- [ ] shenyu-metrics @6freeair2016 
- [ ] shenyu-plugin @choconana 
- [ ] shenyu-register-center @plutokaito 
- [ ] shenyu-spi @heihei180 
- [ ] shenyu-spring-boot-starter  @Cw404
- [ ] shenyu-sync-data-center @JooKS-me
- [ ] shenyu-web  @LXPWing

If you are interested in any of the above modules, please reply ：“ i want to optimize shenyu-xxx” in this and email ：https://lists.apache.org/thread/dr40q6bsrrryn6z19f0d59mor46qwb0s

And then you can create your own issue and break up the optimization of each module into many small tasks. Before that, I suggest you look at: https://shenyu.apache.org/zh/community/code-suggestions

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor) before submitting the PR

**Comment by li-keguo** [comment]
i want to optimize shenyu-examples

**Comment by plutokaito** [comment]
i want to optimize shenyu-register-center

**Comment by JooKS-me** [comment]
I want to optimize `shenyu-sync-data-center` .

**Comment by prospect167** [comment]
i want to optimize sheyun-admin

**Comment by yu199195** [comment]
please repay email ：https://lists.apache.org/thread/dr40q6bsrrryn6z19f0d59mor46qwb0s

**Comment by qinxu2015** [comment]
i want to optimize  shenyu-common

**Comment by LXPWing** [comment]
i want to optimize  shenyu-web

**Comment by qicz** [comment]
`shenyu-client` is mine

**Comment by lxl910128** [comment]
let me try shenyu-integrated-test

**Comment by Cw404** [comment]
i want to optimize shenyu-web

**Comment by choconana** [comment]
I want to optimize shenyu-client.

**Comment by 6freeair2016** [comment]
I want to optimize shenyu-spi

**Comment by songyuequan** [comment]
let me try  shenyu-disruptor please

**Comment by songyuequan** [comment]
let me try shenyu-disruptor please. I have found some warning in this module
| |
songyuequan
|
|
***@***.***
|
签名由网易邮箱大师定制


On 11/16/2021 ***@***.***> wrote：

Volunteer help

Hi Community:

As the functionality of the apache shenyu project becomes more and more perfect.

Now apache shenyu has 100+ sub-projects and the amount of code is getting bigger and bigger.

To enhance the quality and readability of the code,and code design.

The project modules involved in this activity are deliberately launched as follows (code includes test code):

sheyun-admin
shenyu-client
shenyu-common
shenyu-disruptor
shenyu-examples
shenyu-integrated-test
shenyu-loadbalancer
shenyu-metrics
shenyu-plugin
shenyu-register-center
shenyu-spi
shenyu-spring-boot-starter
shenyu-sync-data-center
shenyu-web

If you are interested in any of the above modules, please reply ：“ i want to optimize shenyu-xxx”,
And then you can create your own issue and break up the optimization of each module into many small tasks. Before that, I suggest you look at: https://shenyu.apache.org/zh/community/code-suggestions

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haibo-duan** [comment]
i want to optimize shenyu-loadbalancer

**Comment by heihei180** [comment]
i want optimize `shenyu-spi`

**Comment by heihei180** [comment]
Let me try spi



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 16, 2021 13:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: [apache/incubator-shenyu] 【Code Clean】Remove warning codes in apache shenyu (Issue #2366)




 
Volunteer help
 
Hi Community:
 
As the functionality of the apache shenyu project becomes more and more perfect.
 
Now apache shenyu has 100+ sub-projects and the amount of code is getting bigger and bigger.
 
To enhance the quality and readability of the code,and code design.
 
The project modules involved in this activity are deliberately launched as follows (code includes test code):
  
  sheyun-admin @prospect167 

  shenyu-client @qicz 

 shenyu-common 

 shenyu-disruptor @songyuequan 

 shenyu-examples @li-keguo 

 shenyu-integrated-test 

 shenyu-loadbalancer 

 shenyu-metrics 

 shenyu-plugin 

 shenyu-register-center @plutokaito 

 shenyu-spi @heihei180 

 shenyu-spring-boot-starter 

 shenyu-sync-data-center @JooKS-me 

 shenyu-web 
 
If you are interested in any of the above modules, please reply ：“ i want to optimize shenyu-xxx” in this and email ：https://lists.apache.org/thread/dr40q6bsrrryn6z19f0d59mor46qwb0s
 
And then you can create your own issue and break up the optimization of each module into many small tasks. Before that, I suggest you look at: https://shenyu.apache.org/zh/community/code-suggestions
 
Please read the Contribution Guideline before submitting the PR
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by belary** [comment]
i want to optimize shenyu-loadbalancer

**Comment by yu199195** [comment]
@choconana @Cw404 @6freeair2016 @belary 

thanks，Yours module is already occupied, you can change to another module.   

- [ ] shenyu-metrics
- [ ]  shenyu-plugin  ,   This is a large project is a very core module, which has many sub-projects
- [ ] shenyu-spring-boot-starter  This is a large project is a very core module, which has many sub-projects

**Comment by 6freeair2016** [comment]
ok， I can optimize shenyu-metrics






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-shenyu] 【Code Clean】Remove warning codes in apache shenyu (Issue #2366)





 
@choconana @Cw404 @6freeair2016 @belary
 
thanks，Yours module is already occupied, you can change to another module.
  
 shenyu-metrics
 
  shenyu-plugin  ,   This is a large project is a very core module, which has many sub-projects
 
 shenyu-spring-boot-starter  This is a large project is a very core module, which has many sub-projects
  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cw404** [comment]
ok,  I want optimize shenyu-spring-boot-starter

**Comment by Cw404** [comment]
> @choconana @Cw404 @6freeair2016 @belary
> 
> thanks，Yours module is already occupied, you can change to another module.
> 
> * [ ]  shenyu-metrics
> * [ ]   shenyu-plugin  ,   This is a large project is a very core module, which has many sub-projects
> * [ ]  shenyu-spring-boot-starter  This is a large project is a very core module, which has many sub-projects

ok, I want optimize shenyu-spring-boot-starter

**Comment by choconana** [comment]
> @choconana @Cw404 @6freeair2016 @belary
> 
> thanks，Yours module is already occupied, you can change to another module.
> 
> * [ ]  shenyu-metrics
> * [ ]   shenyu-plugin  ,   This is a large project is a very core module, which has many sub-projects
> * [ ]  shenyu-spring-boot-starter  This is a large project is a very core module, which has many sub-projects

ok, I want to optimize shenyu-plugin

**Comment by choconana** [comment]
Ok, I want to optimize shenyu-plugin.


| |
zdhe9535
|
|
***@***.***
|
签名由网易邮箱大师定制


On 11/16/2021 ***@***.***> wrote：

@***@***.***@***@***.***

thanks，Yours module is already occupied, you can change to another module.

shenyu-metrics
shenyu-plugin , This is a large project is a very core module, which has many sub-projects
shenyu-spring-boot-starter This is a large project is a very core module, which has many sub-projects

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dizent** [comment]
> 我要优化shenyu-examples

Hello, I saw that you applied for optimization shenyu-examples, I want to work with you, can I?

**Comment by dizent** [comment]
I want to optimize the modules under the shenyu plugin；
`shenyu-plugin-httpclient`
`shenyu-plugin-dubbo`
`shenyu-plugin-request`
`shenyu-plugin-uri`

**Comment by li-keguo** [comment]
> > 我要优化shenyu-examples
> 
> Hello, I saw that you applied for optimization shenyu-examples, I want to work with you, can I? @li-keguo

If the landlord agrees, I have no objection.

Examples can be modified very few, it is recommended that you optimize other modules.

**Comment by yu199195** [comment]
@li-keguo @dizent  You can work with each other.

**Comment by songyuequan** [comment]
Hi~   About  optimize  shenyu-plugin you can  see  this   https://github.com/apache/incubator-shenyu/issues/2370   @dizent  @choconana     I  have  list  the  sub module .

**Comment by Berrywrq** [comment]
i want to optimize shenyu-client

**Comment by choconana** [comment]
> Hi~ EveryBody About optimize shenyu-plugin you can see this #2370 @dizent @choconana I have list the sub module .

thank you for dividing this huge module into small tasks

**Comment by YanHui-Yang** [comment]
I want to optimize shenyu-web

**Comment by midnight2104** [comment]
done
